services:
    contao.loader:
        class: Contao\ContaoBundle\Routing\ContaoLoader
        tags:
            - { name: routing.loader }
        arguments: ['@service_container']

    contao.config:
        class: Contao\Config
        factory_class: Contao\Config
        factory_method: getInstance

    contao.listener.output_from_cache:
        class: Contao\ContaoBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }
        arguments: ['@contao.config']

    contao.listener.post_flush:
        class: Contao\ContaoBundle\EventListener\PostFlushListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
