services:
    contao.loader:
        class: Contao\ContaoBundle\Routing\ContaoLoader
        tags:
            - { name: routing.loader }
        arguments: ['@service_container']

    contao.config:
        class: Contao\Config
        factory_class: Contao\Config
        factory_method: getInstance

    contao.listener.post_flush:
        class: Contao\ContaoBundle\EventListener\PostFlushListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.response_exception:
        class: Contao\ContaoBundle\EventListener\ResponseExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
