parameters:
    contao_routing.provider.class: Contao\ContaoBundle\Routing\RouteProvider
    contao_routing.candidates.class: Symfony\Cmf\Component\Routing\Candidates\Candidates

services:
    contao_routing.provider:
        class: %contao_routing.provider.class%
        arguments: ['@contao_routing.candidates', '@contao.config']

    contao_routing.candidates:
        class: %contao_routing.candidates.class%
        arguments: [['[a-z]{2}(\-[A-Z]{2})']]

    contao.config:
        class: Contao\Config
        factory_class: Contao\Config
        factory_method: getInstance

    contao.listener.output_from_cache:
        class: Contao\ContaoBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }
        arguments: ['@contao.config']

    contao.listener.post_flush:
        class: Contao\ContaoBundle\EventListener\PostFlushListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
