parameters:
    contao.loader.class: Contao\ContaoBundle\Routing\ContaoLoader
    contao.config.class: Contao\Config
    contao.database.class: Contao\Database
    contao.environment.class: Contao\Environment

services:
    contao.loader:
        class: %contao.loader.class%
        tags:
            - { name: routing.loader }
        arguments: ['@contao.config']

    contao.config:
        class: %contao.config.class%
        factory_class: %contao.config.class%
        factory_method: getInstance

    contao.database:
        class: %contao.database.class%
        factory_class: %contao.database.class%
        factory_method: getInstance

    contao.environment:
        class: %contao.environment.class%
        factory_class: %contao.environment.class%
        factory_method: getInstance

    contao.listener.output_from_cache:
        class: Contao\ContaoBundle\EventListener\OutputFromCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }
        arguments: ['@contao.config']

    contao.listener.post_flush:
        class: Contao\ContaoBundle\EventListener\PostFlushListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
